### ISSUE TITLE
It won't start

### ISSUE THREAD

**Issue by kimamb** [Pewpews/happypandax#15]
I have no idea, I followed your instructions.

Log:
```
(henv) kim@ubuntu:~/happypandax$ python3 run.py
Traceback (most recent call last):
  File "/home/kim/happypandax/happypanda/server/core/plugins.py", line 261, in _init_plugin
    node.instanced = node.plugin(*node.args, **node.kwargs)
  File "/home/kim/happypandax/plugins/test/HPlugin.py", line 15, in __init__
    self.core.hello()
  File "/home/kim/happypandax/happypanda/server/core/plugins.py", line 387, in __getattr__
    raise exceptions.PluginMethodError(name, "Plugin {}:{} has no such method: {}".format(node.plugin.NAME, node.plugin.ID, key))
happypanda.common.exceptions.PluginMethodError: Plugin Core:9fb4ce2a-fe47-42ef-8c58-e039d999eb19 has no such method: hello

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 11, in <module>
    main.start()
  File "/home/kim/happypandax/happypanda/main.py", line 21, in start
    plugins.plugin_loader(constants.dir_plugin)
  File "/home/kim/happypandax/happypanda/server/core/plugins.py", line 76, in plugin_loader
    return registered.init_plugins()
  File "/home/kim/happypandax/happypanda/server/core/plugins.py", line 226, in init_plugins
    self._init_plugin(node)
  File "/home/kim/happypandax/happypanda/server/core/plugins.py", line 266, in _init_plugin
    raise exceptions.PluginError(node.plugin.NAME, "{}".format(e))
happypanda.common.exceptions.PluginError: Plugin Core:9fb4ce2a-fe47-42ef-8c58-e039d999eb19 has no such method: hello

```

**Comment by Pewpews** [comment]
Hi, I'm sure you're aware of this, but just want to make sure. HPX isn't usable yet and is still under heavy development.

To get rid of the error, please delete `plugins/test` folder.

**Comment by kimamb** [comment]
Ok, you should probably make that more clear in the readme file.

**Comment by Pewpews** [comment]
Yes, you're right.
