### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by wby238** [Pewpews/happypandax#18]
in the step 6 of the building section, it give the following error:

```
Requirement already satisfied: MarkupSafe>=0.23 in c:\program files\python36\lib
\site-packages (from Jinja2>=2.4->Flask==0.11.1->-r requirements.txt (line 2))
Collecting typed-ast<1.1.0,>=1.0.3 (from mypy->transcrypt==3.6.25->-r requiremen
ts.txt (line 9))
  Using cached typed_ast-1.0.3-cp36-cp36m-win_amd64.whl
Installing collected packages: gevent, Werkzeug, itsdangerous, Flask, SQLAlchemy
, sqlalchemy-utils, rarfile, appdirs, karellen-geventws, Mako, python-editor, al
embic, typed-ast, mypy, transcrypt, required, python-dateutil, arrow, python-eng
ineio, python-socketio, happy-socketio, multidict, yarl, async-timeout, aiohttp,
 bencodepy, bitarray, happy-bittorrent
  Running setup.py install for gevent ... error
Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\compat\__init__.py", lin
e 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 69: invalid
 continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\basecommand.py", line 21
5, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip\commands\install.py", li
ne 342, in run
    prefix=options.prefix_path,
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 78
4, in install
    **kwargs
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", lin
e 878, in install
    spinner=spinner,
  File "c:\program files\python36\lib\site-packages\pip\utils\__init__.py", line
 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\program files\python36\lib\site-packages\pip\compat\__init__.py", lin
e 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 69: invalid
 continuation byte
```

OS:Win7 x64, installed py27 and py36.

**Comment by Pewpews** [comment]
Hi, Python 3.6 is not supported. You'll have to download and use Python 3.5 as has been noted in the first step. :) There is no need for py27.

**Comment by wby238** [comment]
thx for your reply.
By the way, I think that you can point out that this project only support python 3.5 directly in the readme file.

**Comment by Pewpews** [comment]
>By the way, I think that you can point out that this project only support python 3.5 directly in the readme

Thanks for the feedback.

>Besides, are there any methods to make both python 3.5 and 3.6 work in windows?

Yes, just download them normally in their respective folders. Put them both in your PATH. Duplicate the `python.exe` files and rename them to their respective versions `python3.5.exe` and `python3.6.exe`. Now when you want to use a specific python version from the cmd, you just write `python3.6 file.py`.

As for pip, they should already be named their respective python versions. Just call `pip3.5` instead of `pip3`.

**Comment by wby238** [comment]
thx.
But there is a new error in the same step now.
```cmd
    C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\bin\cl.exe /c
/nologo /Ox /W3 /GL /DNDEBUG /MD "-Ic:\program files (x86)\python35-32\include"
"-Ic:\program files (x86)\python35-32\include" /Tcbitarray/_bitarray.c /Fobuild\
temp.win32-3.5\Release\bitarray/_bitarray.obj
    _bitarray.c
    c:\program files (x86)\python35-32\include\pyconfig.h(68): fatal error C1083
: 无法打开包括文件: “io.h”: No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\14
.0\\VC\\bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "f:\git\happypandax\env\scripts\python.exe -u -c "import setuptools, tok
enize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-build-qo30h9t7\\b
itarray\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().rep
lace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --re
cord C:\Users\ADMINI~1\AppData\Local\Temp\pip-t4w7bfme-record\install-record.txt
 --single-version-externally-managed --compile --install-headers f:\git\happypan
dax\env\include\site\python3.5\bitarray" failed with error code 1 in C:\Users\AD
MINI~1\AppData\Local\Temp\pip-build-qo30h9t7\bitarray\
```

**Comment by Pewpews** [comment]
Seems like you're having trouble building the C extension `bitarray`. Just download the pre-built binary [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#bitarray). Choose `bitarray‑0.8.1‑cp35‑cp35m‑win32.whl` and once in the HPX env, install with `pip3` like this: `pip3 install path/to/file.whl`.
Also, bookmark this site for future cases like this. Only windows has these issues.

**Comment by wby238** [comment]
thx, Build success.
Expect for the full version.

**Comment by Pewpews** [comment]
https://pewpews.github.io/happypandax/usage.html#starting-up

**Comment by wby238** [comment]
thx, I run it successfully.
Expect for the full version.
