### ISSUE TITLE
GALLERY_LIST not defined

### ISSUE THREAD

**Issue by emmauss** [Pewpews/happypandax#22]
another issue from the recent HPtoHPX script changes. gives this error;
```
 C:\happypandax> python ./HPtoHPX.py happypanda.db hpx.db
Source: happypanda.db
Destination: hpx.db
Connecting to Happypanda database..
Fetching gallery lists..
Traceback (most recent call last):
  File "./HPtoHPX.py", line 678, in <module>
    src_galleries = GalleryDB.get_all_gallery()
  File "./HPtoHPX.py", line 140, in get_all_gallery
    return GalleryDB.gen_galleries(all_gallery, chapters, tags, hashes)
  File "./HPtoHPX.py", line 154, in gen_galleries
    ListDB.query_gallery(gallery)
  File "./HPtoHPX.py", line 323, in query_gallery
    for l in GALLERY_LISTS:
NameError: name 'GALLERY_LISTS' is not defined
```

**Comment by Pewpews** [comment]
fixed now, hehe sorry 
![tumblr_inline_nkyqe6eyjg1qc8ajp](https://user-images.githubusercontent.com/11841002/27261932-6ff20fae-544d-11e7-9529-28bead3db425.gif)
